### ISSUE TITLE
Example links using version 4.1.0 not working 

### ISSUE THREAD

**Issue by joaosegurilho** [UCLOrengoGroup/cath-api-docs#4]
When opening a link with version 4.1.0, used in some examples, returns with "success" false.

Ex: http://www.cathdb.info/version/v4_1_0/api/rest/domain_summary/1cukA01

`
{"success":false,"messages":["DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('host=sinatra;sid=biomapwh','biomap_reader',...) failed: ORA-12532: TNS:invalid argument (DBD ERROR: OCIServerAttach) at /opt/local/perls/build-trunk/lib/site_perl/5.12.2/DBIx/Class/Storage/DBI.pm line 1487. at /opt/local/perls/build-trunk/lib/site_perl/5.12.2/Catalyst/Controller/DBIC/API.pm line 230"]}`

Switching v4_1_0 with v4_2_0 solves the problem.

**Comment by sillitoe** [comment]
Many thanks for reporting - the links have been updated to `v4_3_0`
